FROM node:lts AS builder
ARG BASE_PATH=./
WORKDIR /src
COPY . /src
RUN yarn config set enableTelemetry 0 && \
    yarn install --immutable --network-timeout=300000 --pure-lockfile && \
    NODE_ENV=production yarn build --base=$BASE_PATH

FROM ghcr.io/static-web-server/static-web-server:2-alpine
ARG VERSION=dev
ARG VCS_REF=unknown
ARG BUILD_DATE

LABEL org.opencontainers.image.title="Ketesa" \
      org.opencontainers.image.description="Admin UI for Matrix servers, formerly Synapse Admin" \
      org.opencontainers.image.url="https://ketesa.app" \
      org.opencontainers.image.documentation="https://github.com/etkecc/ketesa#readme" \
      org.opencontainers.image.source="https://github.com/unseal-network/ketesa" \
      org.opencontainers.image.vendor="unseal.network" \
      org.opencontainers.image.authors="etke.cc" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="$VERSION" \
      org.opencontainers.image.revision="$VCS_REF" \
      org.opencontainers.image.created="$BUILD_DATE" \
      org.opencontainers.image.base.name="ghcr.io/static-web-server/static-web-server:2-alpine" \
      description="Admin UI for Matrix servers, formerly Synapse Admin" \
      version="$VERSION" \
      maintainer="etke.cc"

# You can set environment variables as `docker run` arguments too,
# full list: https://static-web-server.net/configuration/environment-variables/
ENV SERVER_FALLBACK_PAGE=/var/public/index.html
ENV SERVER_PORT=8080
ENV SERVER_HEALTH=true

HEALTHCHECK --interval=30s --timeout=10s CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

USER $SERVER_USER_NAME:$SERVER_GROUP_NAME

COPY --from=builder --chown=$SERVER_USER_NAME:$SERVER_GROUP_NAME /src/dist /home/$SERVER_USER_NAME/public
